services:
  - type: web
    name: streamlit-waste-nutrient-app
    env: python
    plan: free
    branch: master  # or 'main' depending on your repo
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.enableCORS false
